### ISSUE TITLE
improve vhf/free-programming-books-lint

### ISSUE THREAD

**Issue by borgified** [EbookFoundation/free-programming-books#5031]
https://github.com/vhf/free-programming-books-lint/blob/master/dist/lint.js#L10

it appears the linter only considers these "languages". we want to expand the list to include other languages/files as well. eg. Vietnamese, C, Java, SQL lists.

looks like https://github.com/vhf/free-programming-books-lint/blob/master/dist/lint.js#L12 determines what language a particular file is, ie. just based on a part of its filename. maybe its possible to expand that list to include vietnamese since that’s not in the first array of langs. (expecting vn)

in our case, [free-courses-vi.md](EbookFoundation/free-courses-vi.md) maybe it should be vn instead to conform to ISO 3166

**Comment by contributor13** [comment]
I would like to fix this issue. Can anyone please suggest what should I do exactly.

**Comment by eshellman** [comment]
@borgified 'vi' is the correct language code (ISO 639-1); ISO 3166 are country codes.
@contributor13 take a look at  https://github.com/vhf/free-programming-books-lint/blob/master/dist/lint.js#L12 and figure out what needs fixing.

**Comment by kadhirash** [comment]
What I came to notice and my understanding is that from the linter code, it excludes the following files: 'README.md', 'CONTRIBUTING.md', 'CODE_OF_CONDUCT.md', 'SUMMARY.md' 

That's why the alphabetization isn't enforced for the above files, but it is for "CODE_OF_CONDUCT-es.md" as seen in #5117.


The langstoAlphabetize var doesn't include 'th' so the Thai resources won't be checked for alphabetization as seen in #3287. 

The other languages added to the repository but not updated to the langsToAlphabetize var won't be alphabetized, such as Thai(th), Farsi(fa_IR), Tamil(ta), etc.

**Comment by eshellman** [comment]
@computamike has contributed a nice fix for pipes to  https://github.com/vhf/free-programming-books-lint/ I've created 3 issues there to address the problems noted in this issue. Folks with Node experience should find these issues pretty easy to fix.

**Comment by eshellman** [comment]
The most recent PR #5207 seems to have missed an alphabetization error - have we messed up the linter by moving the lists into directories?

**Comment by davorpa** [comment]
> @computamike has contributed a nice fix for pipes to https://github.com/vhf/free-programming-books-lint/ I've created 3 issues there to address the problems noted in this issue. Folks with Node experience should find these issues pretty easy to fix.

🎉 Seems all merged/resolved:
- [x] vhf/free-programming-books-lint#23 vhf/free-programming-books-lint#14
- [x] vhf/free-programming-books-lint#59 vhf/free-programming-books-lint#4
- [ ] vhf/free-programming-books-lint#13 vhf/free-programming-books-lint#12 vhf/free-programming-books-lint#15
- [x] vhf/free-programming-books-lint#16 #5239
- [x] vhf/free-programming-books-lint#17 #5239

**Comment by eshellman** [comment]
Thanks for checking!
