### ISSUE TITLE
chore:  hacktoberfest 2021 backlog

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#5762]
When all translations will be stable, we have to remember do some chores after touching common words or translate repo docs.

_Started by @davorpa in https://github.com/EbookFoundation/free-programming-books/pull/5732#discussion_r720701544_

<div align="center" markdown="1">

[![Hacktoberfest 2021](https://img.shields.io/github/hacktoberfest/2021/EbookFoundation/free-programming-books)](https://github.com/EbookFoundation/free-programming-books/pulls?q=is%3Apr+is%3Amerged+created%3A2021-10-01..2021-10-31)

</div>

### Core / Governance

- [x] ci: Get feedback about https://github.com/EbookFoundation/free-programming-books/issues/5176#issuecomment-890391432 / Escape pipes, sharps and other meaningful markdown tokens... in text like headings, resource titles...
- [x] #6590
- [x] #6164. **Improved at**: #6614
- docs: Apply new changes made in english gobernance files (CoC, CONTRIBUTING, HOWTO) to translations
  - [x] Apply #5351  to translations
  - ...
- [x] Consistence format for entry By Lang / By Subject #5602 - #5774
- [x] Title case for product brands #5940, #6384
- [x] #6791
- [x] #6792

### Translation / alphabetization issues

- [x] #6782
- [x] ~Incomplete/partial Indonesian translation #5816 #5898. Maybe #5752 fix it~. Addressed by: #6719
- [x] #6783
- [x] Review #5906 Maybe it uses some Translation service. #6036 
- [x] #7050
- [x] Korean `ko_KR`/`ko_KP` translations #6087. Maybe first commits of #5837 completes some parts of the others (#5908 and #6060 + #6503)
- [x] #5831  https://github.com/EbookFoundation/free-programming-books/commit/d775cb34fbf5eadbdaa465bf46510cc4974151f8#commitcomment-59537594 Minor change in flag emoji markup. **Solved at**: #6619
- [x] Solve review bugs posted after merge https://github.com/EbookFoundation/free-programming-books/pull/6567#pullrequestreview-806520972. **Improved at**: #6618
- [x] #6714 Solve RTL magics linter issues https://github.com/EbookFoundation/free-programming-books/pull/6715#issuecomment-1036637292 https://github.com/vhf/remark-lint-alphabetize-lists/pull/20

### Content / Formating

Improves topic #4579

- [x] Escape Pipes & Typo Trademarks #6577
- [x] Crosslink notes fixup. Addressed at #6789 
- [x] Complete minor changes at https://github.com/EbookFoundation/free-programming-books/pull/6031#pullrequestreview-774520988. **Solved at**: #6271
- [x] ~Normalize CodeWithHarry credits https://github.com/EbookFoundation/free-programming-books/pull/6046#issuecomment-938669946~ Addresed at #6785
- [x] ~Normalize Sicilium resource credits~ Addressed at #6788
- [x] ~Standardize `Learn with Sumit` instructor~. Addressed at #6787
- [x] ~Standardize `Programming with Mosh` instructor~. Addressed at #6790
- [x] Standardize TutorialsPoint resources metadata #6512
- [x] Unglue `POO y MVC en PHP - by Eugenia Bahit` proposed at #6085
- [x] Review UNAM - OpenLibra 404 links / authoring
- [x] Add more resources found here #6129
- [x] #7049
- [x] #7048
- [x] Complete standardization `IDE and Editors` category across files. #5514 #6207 https://github.com/EbookFoundation/free-programming-books/pull/6437#discussion_r736879114
- [x] ~Standardize Flavio Copes' resources: #6479, #6477, #6297, #6331, #5924, #4302~. Addressed at: #6811
- [x] ~Check for module updates about course `Curso completo e atual de HTML5 e CSS3 by Gustavo Guanabara` https://github.com/EbookFoundation/free-programming-books/pull/6513#discussion_r739685946~. Addressed at #6962 
- [x] ~improve podcast hosters #6558~. Addressed at #6834
- [x] improve metadata #6564
- [x] ~Standardize instructor #6572: `Professor Gustavo Guanabara`~ Addressed at: #6809
- [x] ~Use parent url (https://livebook.manning.com/book/flutter-in-action) #6575~ Addressed at:  #6810
- [x] ~Complete instructor #6576: Cláudio Rogério Carvalho Filho. Typo Trademarks~ Addressed at: #6807
- [x] ~:warning: Stale. TODO: recover https://github.com/EbookFoundation/free-programming-books/pull/5760#discussion_r738833235 and https://github.com/EbookFoundation/free-programming-books/pull/5760#discussion_r738833002 resources~. Addressed at: #7002 

### Other

- ...

**Comment by davorpa** [comment]
And finally... backlog is closed with
- #7065
