### ISSUE TITLE
Missing alphabetization supports

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#7050]
There are serveral locale changes/additions since past hacktoberfest

- [ ] ci: Alphabetization support for sinhala (Sri Lanka) #5934. Locale: `si`
- [ ] ci: Alphabetization support for Slovenian #6176. Locale: `sl`
- [ ] ci: Alphabetization support for Bangla. #6021 #5979. Locale: `bl`>`bn`
- [ ] ci: Alphabetization support for Ukrainian. #6542 #6578. Locale: `ua`>`uk`
- [ ] ci: Alphabetization support for Greek. Locale: `gr`>`el`
- [ ] ci: Alphabetization support for Hebrew. #5592 #5590. Locale: `he`
- [ ] ci: Alphabetization support for Bosnian. #5845. Locale: `bs`
- [ ] ci: Alphabetization support for Serbian. #6781. Locale: `sr`
- [ ] ci: Alphabetization support for Khmer (Cambodia). #6156. Locale: `km`
- [ ] ci: Alphabetize Filipino support. #6438 #6504 #6524  #4637. Locale: `fil`
- [ ] ci: Alphabetize Malayalam (India) support. #6681. Locale: `ml`
- [ ] ci: Alphabetize Latvian support (via #6979)

For all those locales the selected ICU table is `english` (the default)

So recheck, fix and register new languages or changes to our linter

**Comment by LuigiImVector** [comment]
To avoid having to do this again in the future we can alphabetize all the languages, as on [`free-programming-books-parser/languages.js`](https://github.com/EbookFoundation/free-programming-books-parser/blob/main/languages.js).

**Comment by davorpa** [comment]
> To avoid having to do this again in the future we can alphabetize all the languages, as on [`free-programming-books-parser/languages.js`](https://github.com/EbookFoundation/free-programming-books-parser/blob/main/languages.js?rgh-link-date=2022-09-02T15%3A57%3A22Z).

In that case, maybe the problem would be the ICU tables. There are one for each one of languages?

I'm in pro to transfer linter project to this organization and then don't have blocking issues.

What do you think @eshellman @vhf?

**Comment by LuigiImVector** [comment]
> There are one for each one of languages?

There seems to be all the languages with the correct codes

**Comment by eshellman** [comment]
seems like we should do this, to the extent that we have skills.
